services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"

 
  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - MONGO_URL=mongodb+srv://mike_zvz:mn0tavRJAiW1bsEr@tasks.vnvee.mongodb.net/task-tracker
    ports:
      - "80:80"
    depends_on:
      - backend